### ISSUE TITLE
Debuffs in BFA

### ISSUE THREAD

**Issue by milioner1** [ascott18/Masque-Skinner-ShadowedUF#1]
All the debuffs as of 8.2.5 are simply square blotches of either solid red or solid blue. Buffs are working beautifully, however. What might be causing this?

**Comment by ascott18** [comment]
You'll have to share what skin you're using and a screenshot of what you're seeing. Everything is working fine for me.

**Comment by milioner1** [comment]
This is the issue I was talking about. It's related to the Masque Skinner for ShadowedUF (the buggy debuffs are attached to the target frame, not the nameplate below it, in case that's confusing). For some reason the solid squares aren't applying to the buffs, which seem to be working flawlessly.
Other notable addons I'm running besides SUF are certain modules of ElvUI which I decided to leave toggled on, Threatplates, Quartz, BigDebuffs, Dominos, Gladius, OPie, Omnibar, OmniCC, Weakauras, MoveAnything and DBM; I don't know if that information is useful, but I figured I'd affix it on the off-chance that some of them may conflict with your skin.
    On Monday, December 16, 2019, 12:43:59 AM GMT+2, Andrew Scott <notifications@github.com> wrote:  
 
 
You'll have to share what skin you're using and a screenshot of what you're seeing. Everything is working fine for me.

**Comment by ascott18** [comment]
> This is the issue I was talking about. It's related to the Masque Skinner for ShadowedUF

Yes, I gathered as much given that this is the project where you've logged this issue.

I still can't help you if you don't provide the information I asked for.

Just to be clear, this addon is not a skin. It sets up ShadowedUF with Masque so that Masque can know how to skin the buff/debuff frames of SUF, but this addon is not a skin nor does it apply skins. It simply tells Masque about the different parts of SUF that are skinnable.

**Comment by milioner1** [comment]
I was sure I'd provided you with the information you asked for.
"You'll have to share what skin you're using and a screenshot of what you're seeing."
I'll assume that by skin, you mean which selection I chose from the dropdown menu in the SUF section of the Masque settings, because otherwise I wouldn't know what other information you might need.
Clean Icons - Square is my selection for all addons, but I downloaded another module of Clean Icons called "Clean Icons - Thin", the installation of which differs from most other Masque skins in that it requires you to unzip its files outside the AddOn directory, making it like so:


The highlighted files are part of the "Thin" Masque skin.
It doesn't add the Thin option to the Masque menu though, it's supposed to work some other way. Not even sure how, really. Could this be the reason why my debuffs are bugging out?    On Monday, December 16, 2019, 10:13:14 PM GMT+2, Andrew Scott <notifications@github.com> wrote:  
 
 

This is the issue I was talking about. It's related to the Masque Skinner for ShadowedUF
Yes, I gathered as much given that this is the project where you've logged this issue.


I still can't help you if you don't provide the information I asked for.

Just to be clear, this addon is not a skin. It sets up ShadowedUF with Masque so that Masque can know how to skin the buff/debuff frames of SUF, but this addon is not a skin nor does it apply skins. It simply tells Masque about the different parts of SUF that are skinnable.

**Comment by ascott18** [comment]
If you're trying to include images, you're going to need to respond to the issue on GitHub. Email replies to issue notifications aren't a full replacement for the full issue interface on GitHub.com. I have no way of seeing any attachments you may have included in your email - they just go into the void.

**Comment by milioner1** [comment]
Oh, lol. I was attaching images to both replies :P I'll leave them on the GitHub thing.
    On Tuesday, December 17, 2019, 07:17:14 PM GMT+2, Andrew Scott <notifications@github.com> wrote:  
 
 
If you're trying to include images, you're going to need to respond to the issue on GitHub. Email replies to issue notifications aren't a full replacement for the full issue interface on GitHub.com.

**Comment by milioner1** [comment]
**To start over, I'll just condense the whole dialogue into a single comment for comfort's sake. This was the image I'd attached to the following comment:**

![image](https://user-images.githubusercontent.com/58864610/71035707-b9533a00-2124-11ea-83ca-15c48719aef4.png)

"This is the issue I was talking about. It's related to the Masque Skinner for ShadowedUF (the buggy debuffs are attached to the target frame, not the nameplate below it, in case that's confusing). For some reason the solid squares aren't applying to the buffs, which seem to be working flawlessly.

Other notable addons I'm running besides SUF are certain modules of ElvUI which I decided to leave toggled on, Threatplates, Quartz, BigDebuffs, Dominos, Gladius, OPie, Omnibar, OmniCC, Weakauras, MoveAnything and DBM; I don't know if that information is useful, but I figured I'd affix it on the off-chance that some of them may conflict with your skin."

**To which you replied with:**

"Yes, I gathered as much given that this is the project where you've logged this issue.

I still can't help you if you don't provide the information I asked for.

Just to be clear, this addon is not a skin. It sets up ShadowedUF with Masque so that Masque can know how to skin the buff/debuff frames of SUF, but this addon is not a skin nor does it apply skins. It simply tells Masque about the different parts of SUF that are skinnable."

**My next reply was accompanied by the following:**

"I was sure I'd provided you with the information you asked for.

'You'll have to share what skin you're using and a screenshot of what you're seeing.'

I'll assume that by skin, you mean which selection I chose from the dropdown menu in the SUF section of the Masque settings, because otherwise I wouldn't know what other information you might need.

Clean Icons - Square is my selection for all addons, but I downloaded another module of Clean Icons called "Clean Icons - Thin", the installation of which differs from most other Masque skins in that it requires you to unzip its files outside the AddOn directory, making it like so:

![image](https://user-images.githubusercontent.com/58864610/71035763-dab42600-2124-11ea-9de7-f43b24bfa705.png)

The highlighted files are part of the "Thin" Masque skin.

It doesn't add the Thin option to the Masque menu though, it's supposed to work some other way. Not even sure how, really. Could this be the reason why my debuffs are bugging out?"


**Sorry for the misunderstanding, I was sure you'd been emailing me as well this whole time haha.**

**Comment by ascott18** [comment]
Sorry about the confusion - seems like poor UX on GitHub's part to not inform you that your images aren't included when you reply via email.

For this issue, its a bug with https://www.wowinterface.com/downloads/info21963-MasqueCleanIcons.html - I was able to reproduce this immediately after installing it and changing Masque to use it as my skin. In particular, it doesn't seem to be correctly skinning the colored borders that SUF places on debuffs that indicate the debuff type. That's why you see different colors - red for physical, blue for magic, orange for disease, and so on.

Don't know what in particular it is doing wrong, but you can follow up with the author of Masque: Clean Icons. No other skin that I have installed is broken in this way.

The version of Clean Icons that you had to install in a special way is a texture replacer - it overrides the actual game files for every icon in the game with a version that is pre-styled in a certain way. This lets it work for addons that don't support Masque.
